[Settings]

;映像メモリのサイズを MB 単位で指定します (デフォルト : 10)
MemorySize=

;AviUtl.exe のパスを指定します。
AviUtlPath=C:\????????

;実行時に AviUtl をアクティブにする (デフォルト : 1)
;0 = 無効
;1 = 有効
Activate=1

;TVTest の終了時に AviUtl も終了させる (デフォルト : 0)
;0 = 無効
;1 = 有効
AutoClose=0
